"""
Bantz — Hyprland Config Generator (#365)

Generates all configuration files needed for the Bantz Hyprland desktop:

- ``hyprland.conf``  — tiling rules, window rules, keybindings, exec-once
- ``kitty.conf``     — Bantz-themed kitty terminal configuration
- ``waybar/config``  — top status bar with Bantz status, clock, workspaces
- ``waybar/style.css`` — dark theme waybar stylesheet
- ``eww/eww.yuck``  — widget layout (news, calendar, system stats)
- ``eww/eww.scss``  — widget stylesheet
- ``mako/config``   — notification daemon config

Each ``generate_*`` method returns the config as a string. The ``deploy``
method writes all files to the target directory (default: ``~/.config``).
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

log = logging.getLogger("bantz.desktop.generator")

# ── Default Bantz colour palette ──────────────────────────────────────────────

COLORS = {
    "bg": "#0d1117",
    "bg_dark": "#010409",
    "bg_light": "#161b22",
    "fg": "#c9d1d9",
    "fg_dim": "#8b949e",
    "accent": "#58a6ff",
    "accent_alt": "#79c0ff",
    "green": "#3fb950",
    "red": "#f85149",
    "yellow": "#d29922",
    "orange": "#db6d28",
    "purple": "#bc8cff",
    "border": "#30363d",
    "border_active": "#58a6ff",
    "transparent": "rgba(13, 17, 23, 0.85)",
}


class ConfigGenerator:
    """Generate all Hyprland desktop config files for Bantz."""

    def __init__(
        self,
        *,
        terminal: str = "kitty",
        terminal_class: str = "bantz-chat",
        bantz_command: str = "bantz",
        left_ratio: float = 0.6,
        wallpaper: str = "",
        colors: dict[str, str] | None = None,
        monitor_config: str = ",preferred,auto,1",
    ) -> None:
        self.terminal = terminal
        self.terminal_class = terminal_class
        self.bantz_command = bantz_command
        self.left_ratio = left_ratio
        self.wallpaper = wallpaper
        self.colors = {**COLORS, **(colors or {})}
        self.monitor_config = monitor_config

    # ── Hyprland main config ──────────────────────────────────────────────

    def generate_hyprland_conf(self) -> str:
        """Generate ``hyprland.conf`` with tiling + Bantz window rules."""
        c = self.colors
        return f"""\
# ═══════════════════════════════════════════════════════════════════════
# Bantz Hyprland Desktop — auto-generated by bantz --setup hyprland
# Issue #365 — Hyprland Desktop Environment
# ═══════════════════════════════════════════════════════════════════════

# ── Monitor ───────────────────────────────────────────────────────────
monitor = {self.monitor_config}

# ── Environment ───────────────────────────────────────────────────────
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# ── Input ─────────────────────────────────────────────────────────────
input {{
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0
    touchpad {{
        natural_scroll = true
    }}
}}

# ── General ───────────────────────────────────────────────────────────
general {{
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb({c['border_active'].lstrip('#')})
    col.inactive_border = rgb({c['border'].lstrip('#')})
    layout = dwindle
    allow_tearing = false
}}

# ── Decoration ────────────────────────────────────────────────────────
decoration {{
    rounding = 8
    blur {{
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = false
    }}
    shadow {{
        enabled = true
        range = 20
        render_power = 3
        color = rgba(0, 0, 0, 0.55)
    }}

    active_opacity = 0.95
    inactive_opacity = 0.88
    fullscreen_opacity = 1.0
}}

# ── Animations ────────────────────────────────────────────────────────
animations {{
    enabled = true
    bezier = bantzSmooth, 0.25, 0.1, 0.25, 1.0
    bezier = bantzSnap, 0.4, 0.0, 0.2, 1.0
    animation = windows, 1, 4, bantzSmooth, slide
    animation = windowsOut, 1, 4, bantzSnap, slide
    animation = fade, 1, 3, bantzSmooth
    animation = workspaces, 1, 4, bantzSmooth, slidevert
    animation = border, 1, 5, bantzSmooth
    animation = borderangle, 1, 30, bantzSmooth, loop
}}

# ── Dwindle Layout ────────────────────────────────────────────────────
dwindle {{
    pseudotile = true
    preserve_split = true
    force_split = 2
    split_width_multiplier = {self.left_ratio / (1.0 - self.left_ratio):.2f}
}}

# ── Misc ──────────────────────────────────────────────────────────────
misc {{
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}}

# ═══════════════════════════════════════════════════════════════════════
# WINDOW RULES — Bantz Desktop Layout
# ═══════════════════════════════════════════════════════════════════════

# Bantz chat terminal — always left, 60% width
windowrulev2 = tile, class:^({self.terminal_class})$
windowrulev2 = size 60% 100%, class:^({self.terminal_class})$
windowrulev2 = move 0 0, class:^({self.terminal_class})$
windowrulev2 = opacity 0.95, class:^({self.terminal_class})$
windowrulev2 = bordercolor rgb({c['accent'].lstrip('#')}), class:^({self.terminal_class})$

# Eww widgets — right column, no border, no focus steal
windowrulev2 = nofocus, class:^(eww-.*)$
windowrulev2 = noshadow, class:^(eww-.*)$
windowrulev2 = noborder, class:^(eww-.*)$
windowrulev2 = pin, class:^(eww-.*)$
windowrulev2 = float, class:^(eww-.*)$

# Mako notifications — float above all
windowrulev2 = float, class:^(mako)$
windowrulev2 = pin, class:^(mako)$

# ═══════════════════════════════════════════════════════════════════════
# KEYBINDINGS
# ═══════════════════════════════════════════════════════════════════════

$mod = SUPER

# -- Core --
bind = $mod, Return, exec, {self.terminal} --class {self.terminal_class} -e {self.bantz_command}
bind = $mod, Q, killactive
bind = $mod SHIFT, Q, exit
bind = $mod, V, togglefloating
bind = $mod, F, fullscreen, 0
bind = $mod, P, pseudo
bind = $mod, J, togglesplit

# -- Focus --
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

# -- Workspaces --
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# -- Resize --
bind = $mod CTRL, h, resizeactive, -40 0
bind = $mod CTRL, l, resizeactive, 40 0
bind = $mod CTRL, k, resizeactive, 0 -40
bind = $mod CTRL, j, resizeactive, 0 40

# -- Mouse --
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# -- Screenshot (grim) --
bind = , Print, exec, grim -g "$(slurp)" - | wl-copy
bind = $mod, Print, exec, grim - | wl-copy

# -- Bantz-specific --
bind = $mod, B, exec, {self.terminal} --class {self.terminal_class} -e {self.bantz_command}
bind = $mod SHIFT, B, exec, bantz --doctor

# ═══════════════════════════════════════════════════════════════════════
# AUTO-LAUNCH (exec-once)
# ═══════════════════════════════════════════════════════════════════════

# Wallpaper
exec-once = swww-daemon
{"exec-once = swww img " + self.wallpaper + " --transition-type grow --transition-pos 0.5,0.5" if self.wallpaper else "# No wallpaper configured — set BANTZ_HYPRLAND_WALLPAPER"}

# Status bar
exec-once = waybar -c ~/.config/waybar/config -s ~/.config/waybar/style.css

# Notification daemon
exec-once = mako

# Eww widgets (right column panels)
exec-once = eww daemon
exec-once = sleep 1 && eww open-many bantz-news bantz-calendar bantz-stats

# ── Main: Bantz chat terminal ────────────────────────────────────────
exec-once = {self.terminal} --class {self.terminal_class} -e {self.bantz_command}
"""

    # ── Kitty terminal config ─────────────────────────────────────────────

    def generate_kitty_conf(self) -> str:
        """Generate a Bantz-themed ``kitty.conf``."""
        c = self.colors
        return f"""\
# ═══════════════════════════════════════════════════════════════════════
# Kitty — Bantz Desktop Theme
# Auto-generated by bantz --setup hyprland (#365)
# ═══════════════════════════════════════════════════════════════════════

# ── Font ──────────────────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ── Window ────────────────────────────────────────────────────────────
window_padding_width 8
background_opacity   0.92
dynamic_background_opacity yes
confirm_os_window_close 0
remember_window_size no
initial_window_width  120c
initial_window_height 40c
placement_strategy    center
hide_window_decorations yes

# ── Scrollback ────────────────────────────────────────────────────────
scrollback_lines 10000

# ── Cursor ────────────────────────────────────────────────────────────
cursor_shape     beam
cursor_blink_interval 0.5

# ── URL ───────────────────────────────────────────────────────────────
url_style curly
open_url_with default
detect_urls yes

# ── Bell ──────────────────────────────────────────────────────────────
enable_audio_bell no
visual_bell_duration 0.0

# ── Colours — Bantz Dark Theme ────────────────────────────────────────
foreground {c['fg']}
background {c['bg']}
selection_foreground {c['bg']}
selection_background {c['accent']}
cursor {c['accent']}
cursor_text_color {c['bg']}
url_color {c['accent_alt']}

# black
color0  {c['bg_dark']}
color8  {c['fg_dim']}
# red
color1  {c['red']}
color9  {c['red']}
# green
color2  {c['green']}
color10 {c['green']}
# yellow
color3  {c['yellow']}
color11 {c['yellow']}
# blue
color4  {c['accent']}
color12 {c['accent_alt']}
# magenta
color5  {c['purple']}
color13 {c['purple']}
# cyan
color6  {c['accent_alt']}
color14 {c['accent_alt']}
# white
color7  {c['fg']}
color15 #ffffff

# ── Tab bar ───────────────────────────────────────────────────────────
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   {c['bg']}
active_tab_background   {c['accent']}
inactive_tab_foreground {c['fg_dim']}
inactive_tab_background {c['bg_light']}
"""

    # ── Waybar config ─────────────────────────────────────────────────────

    def generate_waybar_config(self) -> str:
        """Generate waybar config JSON (top status bar)."""
        import json
        config: dict[str, Any] = {
            "layer": "top",
            "position": "top",
            "height": 32,
            "spacing": 4,
            "modules-left": ["hyprland/workspaces", "hyprland/window"],
            "modules-center": ["clock"],
            "modules-right": [
                "custom/bantz-status",
                "pulseaudio",
                "network",
                "cpu",
                "memory",
                "temperature",
                "tray",
            ],
            "hyprland/workspaces": {
                "format": "{icon}",
                "on-click": "activate",
                "format-icons": {
                    "1": "🤖",
                    "2": "🌐",
                    "3": "📁",
                    "4": "🎵",
                    "5": "⚙️",
                    "active": "●",
                    "default": "○",
                },
            },
            "hyprland/window": {
                "format": "{}",
                "max-length": 50,
            },
            "clock": {
                "format": "{:%H:%M}",
                "format-alt": "{:%A, %B %d, %Y — %H:%M:%S}",
                "tooltip-format": "<tt><small>{calendar}</small></tt>",
                "calendar": {
                    "mode": "year",
                    "mode-mon-col": 3,
                    "weeks-pos": "right",
                    "format": {
                        "today": "<span color='#58a6ff'><b>{}</b></span>",
                    },
                },
            },
            "custom/bantz-status": {
                "exec": "bantz-widget-status",
                "interval": 5,
                "format": "🤖 {}",
                "tooltip": True,
                "return-type": "json",
            },
            "cpu": {
                "format": " {usage}%",
                "interval": 5,
                "tooltip": True,
            },
            "memory": {
                "format": " {percentage}%",
                "interval": 10,
                "tooltip-format": "{used:.1f}G / {total:.1f}G",
            },
            "temperature": {
                "critical-threshold": 80,
                "format": " {temperatureC}°C",
                "format-critical": " {temperatureC}°C",
            },
            "network": {
                "format-wifi": "  {signalStrength}%",
                "format-ethernet": " {ipaddr}",
                "format-disconnected": "⚠ Disconnected",
                "tooltip-format": "{ifname}: {ipaddr}/{cidr}",
            },
            "pulseaudio": {
                "format": "{icon} {volume}%",
                "format-muted": "🔇",
                "format-icons": {"default": ["🔈", "🔉", "🔊"]},
                "on-click": "pavucontrol",
            },
            "tray": {
                "icon-size": 16,
                "spacing": 8,
            },
        }
        return json.dumps(config, indent=2) + "\n"

    def generate_waybar_style(self) -> str:
        """Generate waybar CSS stylesheet."""
        c = self.colors
        return f"""\
/* ═══════════════════════════════════════════════════════════════════════
 * Waybar — Bantz Desktop Theme (#365)
 * Auto-generated by bantz --setup hyprland
 * ═══════════════════════════════════════════════════════════════════════ */

* {{
    font-family: "JetBrainsMono Nerd Font", "Font Awesome 6 Free", sans-serif;
    font-size: 13px;
    min-height: 0;
}}

window#waybar {{
    background: {c['transparent']};
    color: {c['fg']};
    border-bottom: 2px solid {c['border']};
}}

#workspaces button {{
    padding: 0 8px;
    color: {c['fg_dim']};
    background: transparent;
    border: none;
    border-radius: 4px;
    margin: 2px;
}}

#workspaces button.active {{
    color: {c['accent']};
    background: {c['bg_light']};
    font-weight: bold;
}}

#workspaces button:hover {{
    background: {c['bg_light']};
}}

#clock {{
    color: {c['fg']};
    font-weight: bold;
}}

#custom-bantz-status {{
    color: {c['green']};
    padding: 0 10px;
    font-weight: bold;
}}

#custom-bantz-status.thinking {{
    color: {c['yellow']};
    animation: pulse 1.5s ease-in-out infinite;
}}

@keyframes pulse {{
    0%, 100% {{ opacity: 1; }}
    50% {{ opacity: 0.5; }}
}}

#cpu, #memory, #temperature, #network, #pulseaudio {{
    padding: 0 8px;
    color: {c['fg_dim']};
}}

#cpu.warning, #memory.warning {{
    color: {c['yellow']};
}}

#cpu.critical, #memory.critical, #temperature.critical {{
    color: {c['red']};
}}

#tray {{
    padding: 0 4px;
}}

#tray > .passive {{
    -gtk-icon-effect: dim;
}}

tooltip {{
    background: {c['bg']};
    border: 1px solid {c['border']};
    border-radius: 6px;
    color: {c['fg']};
}}
"""

    # ── Eww widgets ───────────────────────────────────────────────────────

    def generate_eww_yuck(self) -> str:
        """Generate ``eww.yuck`` — widget layout for right column panels."""
        return """\
;; ═══════════════════════════════════════════════════════════════════════
;; Eww — Bantz Desktop Widgets (#365)
;; Auto-generated by bantz --setup hyprland
;; ═══════════════════════════════════════════════════════════════════════

;; ── Polling variables ────────────────────────────────────────────────
(defpoll news-data   :interval "5m"  "bantz-widget-data news")
(defpoll weather-data :interval "10m" "bantz-widget-data weather")
(defpoll calendar-data :interval "2m" "bantz-widget-data calendar")
(defpoll todo-data    :interval "30s" "bantz-widget-data todos")
(defpoll cpu-usage    :interval "3s"  "bantz-widget-data cpu")
(defpoll ram-usage    :interval "3s"  "bantz-widget-data ram")
(defpoll disk-usage   :interval "30s" "bantz-widget-data disk")
(defpoll gpu-data     :interval "5s"  "bantz-widget-data gpu")
(defpoll net-data     :interval "5s"  "bantz-widget-data network")
(defpoll bantz-status :interval "3s"  "bantz-widget-data status")

;; ── News / Weather Widget ────────────────────────────────────────────
(defwidget news-panel []
  (box :class "panel news-panel" :orientation "v" :space-evenly false
    (box :class "panel-header"
      (label :text "📰 Headlines & Weather"))
    (box :class "weather-row" :orientation "h" :space-evenly true
      (label :text weather-data :wrap true))
    (scroll :vscroll true :height 200
      (box :orientation "v" :space-evenly false
        (label :text news-data :wrap true :xalign 0)))))

;; ── Calendar / Todo Widget ───────────────────────────────────────────
(defwidget calendar-panel []
  (box :class "panel calendar-panel" :orientation "v" :space-evenly false
    (box :class "panel-header"
      (label :text "📅 Calendar & Todos"))
    (calendar :class "cal" :show-heading true :show-details true)
    (box :class "section-label"
      (label :text "☑️ Upcoming Events"))
    (scroll :vscroll true :height 120
      (box :orientation "v" :space-evenly false
        (label :text calendar-data :wrap true :xalign 0)))
    (box :class "section-label"
      (label :text "📋 Todos"))
    (scroll :vscroll true :height 100
      (box :orientation "v" :space-evenly false
        (label :text todo-data :wrap true :xalign 0)))))

;; ── System Stats Widget ──────────────────────────────────────────────
(defwidget stats-panel []
  (box :class "panel stats-panel" :orientation "v" :space-evenly false
    (box :class "panel-header"
      (label :text "📊 System Stats"))
    ;; CPU
    (box :class "stat-row" :orientation "h" :space-evenly false
      (label :text " CPU" :width 80)
      (progress :value cpu-usage :orientation "h")
      (label :text "${cpu-usage}%%" :width 50))
    ;; RAM
    (box :class "stat-row" :orientation "h" :space-evenly false
      (label :text " RAM" :width 80)
      (progress :value ram-usage :orientation "h")
      (label :text "${ram-usage}%%" :width 50))
    ;; Disk
    (box :class "stat-row" :orientation "h" :space-evenly false
      (label :text " Disk" :width 80)
      (progress :value disk-usage :orientation "h")
      (label :text "${disk-usage}%%" :width 50))
    ;; GPU
    (box :class "stat-row" :orientation "h" :space-evenly false
      (label :text "🎮 GPU" :width 80)
      (label :text gpu-data :width 150))
    ;; Network
    (box :class "stat-row" :orientation "h" :space-evenly false
      (label :text " Net" :width 80)
      (label :text net-data :width 150))
    ;; Bantz Status
    (box :class "bantz-status-row" :orientation "h" :space-evenly false
      (label :text "🤖 Bantz" :width 80)
      (label :text bantz-status :width 150))))

;; ═══════════════════════════════════════════════════════════════════════
;; WINDOWS — positioned on the right 40% of the screen
;; ═══════════════════════════════════════════════════════════════════════

(defwindow bantz-news
  :monitor 0
  :geometry (geometry :x "-8px" :y "40px" :width "38%" :height "30%" :anchor "top right")
  :stacking "bg"
  :exclusive false
  :focusable false
  :namespace "eww-bantz-news"
  (news-panel))

(defwindow bantz-calendar
  :monitor 0
  :geometry (geometry :x "-8px" :y "33%" :width "38%" :height "34%" :anchor "top right")
  :stacking "bg"
  :exclusive false
  :focusable false
  :namespace "eww-bantz-calendar"
  (calendar-panel))

(defwindow bantz-stats
  :monitor 0
  :geometry (geometry :x "-8px" :y "-8px" :width "38%" :height "30%" :anchor "bottom right")
  :stacking "bg"
  :exclusive false
  :focusable false
  :namespace "eww-bantz-stats"
  (stats-panel))
"""

    def generate_eww_scss(self) -> str:
        """Generate ``eww.scss`` — Bantz-themed widget styles."""
        c = self.colors
        return f"""\
// ═══════════════════════════════════════════════════════════════════════
// Eww — Bantz Desktop Widget Styles (#365)
// Auto-generated by bantz --setup hyprland
// ═══════════════════════════════════════════════════════════════════════

$bg: {c['bg']};
$bg-light: {c['bg_light']};
$fg: {c['fg']};
$fg-dim: {c['fg_dim']};
$accent: {c['accent']};
$green: {c['green']};
$red: {c['red']};
$yellow: {c['yellow']};
$border: {c['border']};

* {{
  all: unset;
  font-family: "JetBrainsMono Nerd Font", sans-serif;
  font-size: 13px;
}}

.panel {{
  background: rgba(13, 17, 23, 0.88);
  border: 1px solid $border;
  border-radius: 10px;
  padding: 12px;
  color: $fg;
}}

.panel-header {{
  font-size: 15px;
  font-weight: bold;
  color: $accent;
  padding-bottom: 8px;
  border-bottom: 1px solid $border;
  margin-bottom: 8px;
}}

.section-label {{
  font-size: 12px;
  color: $fg-dim;
  padding: 6px 0 4px 0;
  font-weight: bold;
}}

// ── Stats panel ──────────────────────────────────────────────────────
.stat-row {{
  padding: 4px 0;

  progress {{
    min-width: 120px;
    min-height: 8px;
    border-radius: 4px;
    background: $bg-light;
    margin: 0 8px;

    trough {{
      min-height: 8px;
      border-radius: 4px;
      background: $bg-light;
    }}

    progress {{
      min-height: 8px;
      border-radius: 4px;
      background: $accent;
    }}
  }}
}}

.bantz-status-row {{
  padding: 8px 0 4px 0;
  border-top: 1px solid $border;
  margin-top: 4px;
}}

// ── News panel ───────────────────────────────────────────────────────
.weather-row {{
  padding: 6px;
  background: $bg-light;
  border-radius: 6px;
  margin-bottom: 8px;
}}

// ── Calendar panel ───────────────────────────────────────────────────
.cal {{
  padding: 4px;
  color: $fg;

  .header {{
    color: $accent;
    font-weight: bold;
  }}

  .day {{
    color: $fg-dim;
    &.current {{
      color: $accent;
      font-weight: bold;
    }}
  }}
}}
"""

    # ── Mako notification config ──────────────────────────────────────────

    def generate_mako_config(self) -> str:
        """Generate mako notification daemon config."""
        c = self.colors
        return f"""\
# ═══════════════════════════════════════════════════════════════════════
# Mako — Bantz Desktop Notifications (#365)
# Auto-generated by bantz --setup hyprland
# ═══════════════════════════════════════════════════════════════════════

sort=-time
layer=overlay
anchor=top-right
width=380
height=120
margin=8
padding=12
border-size=2
border-radius=8
border-color={c['border_active']}
background-color={c['bg']}ee
text-color={c['fg']}
default-timeout=8000
font=JetBrainsMono Nerd Font 11
icons=1
icon-path=/usr/share/icons/Papirus-Dark
max-icon-size=48
markup=1
actions=1
format=<b>%s</b>\\n%b
max-visible=4

[urgency=low]
border-color={c['border']}
background-color={c['bg_light']}dd
default-timeout=5000

[urgency=high]
border-color={c['red']}
background-color={c['bg']}ee
default-timeout=0

[app-name=bantz]
border-color={c['accent']}
background-color={c['bg']}ee
default-timeout=10000
"""

    # ── Deploy all configs ────────────────────────────────────────────────

    def generate_all(self) -> dict[str, str]:
        """Return all config files as {relative_path: content}."""
        return {
            "hypr/hyprland.conf": self.generate_hyprland_conf(),
            "kitty/kitty.conf": self.generate_kitty_conf(),
            "waybar/config": self.generate_waybar_config(),
            "waybar/style.css": self.generate_waybar_style(),
            "eww/eww.yuck": self.generate_eww_yuck(),
            "eww/eww.scss": self.generate_eww_scss(),
            "mako/config": self.generate_mako_config(),
        }

    def deploy(
        self,
        config_dir: str | Path | None = None,
        *,
        dry_run: bool = False,
        backup: bool = True,
    ) -> list[Path]:
        """Write all config files to ``~/.config/`` (or given dir).

        Returns list of written file paths.  If ``dry_run`` is True,
        returns what *would* be written without writing.
        """
        base = Path(config_dir) if config_dir else Path.home() / ".config"
        written: list[Path] = []
        for relpath, content in self.generate_all().items():
            target = base / relpath
            if dry_run:
                written.append(target)
                log.info("[dry-run] Would write %s (%d bytes)", target, len(content))
                continue
            # Backup existing
            if backup and target.exists():
                bak = target.with_suffix(target.suffix + ".bak")
                target.rename(bak)
                log.info("Backed up %s → %s", target, bak)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
            written.append(target)
            log.info("Wrote %s (%d bytes)", target, len(content))
        return written
